---
tomcat:
  install_dir: /etc/tomcat6
  share_dir: /usr/share/tomcat6
  service_name: tomcat6
  server_port: 8005
  redirect_port: 8443
  properties_dir: appconf
  lib_dir: /var/lib/tomcat6
  app_base_dir_name: appBase
  cache_dir: /var/cache/tomcat6

