---
env: vm
env_name: java-{{ env }}
base_domain: "{{ env }}.openconext.org"

# on the VM we use the same certificate for all domains under base_domain.
tls_https:
  key_name: star.{{ base_domain }}.key
  crt_name: star.{{ base_domain }}.pem
  bundle_name: star.{{ base_domain }}_ca_bundle.pem

# when using multiple certificates list them all (and their bundles) under tls.certificates
tls:
  cert_path: /etc/pki/tls/certs
  cert_private_path: /etc/pki/tls/private
  certificates:
    - "{{ tls_https.crt_name }}"
    - "{{ tls_https.bundle_name }}"
  private_keys:
    - "{{ tls_https.key_name }}"


tomcat_apps:
  - api
  - teams
  - grouper
  - mujina-sp
  - mujina-idp

# shibboleth
shibboleth_apps:
  - teams
shib:
  engine_domain: "{{ base_domain }}"


# tomcat
keystore_password: ACAvoLNaJSARHx9BSmUpockTtDLp_LSmx9DkGnvuk62VtREBsK_IRVr1MM9AAsbb__Xsc4pp5YPa

# versions of installed apps
teams_version: 4.0.6
#teams_snapshot_timestamp: 20141112.081923-4

api_version: 4.0.1
api_snapshot_timestamp: 20150115.230128-349

mujina_version: 4.0.2
#mujina_snapshot_timestamp

##
# VM config for the teams app
##
teams:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"
  team_db_password: ACAvoLNsq2VCDZAEwUldTSn2waM9mIazqxmykoTbpZQaPuIV0ye_7YswiMFrTD1pbXE_UGBW2OTb
  team_db_host: localhost
  eb_db_password: ACAvoLPY26q3FD4KZkXCJtWpQi7GW10qpS8LgW5IEDGherQr8yv5KDlCpdYoyZ8Qts28kfvFdRxm
  eb_db_host: db.{{ base_domain }}
  mail_server: localhost
  group_name_context: "urn:collab:group:test.surfteams.nl:"

engineblock:
  idp_url: https://engine.{{ base_domain }}/authentication/idp/single-sign-on
  idp_entity_id: https://engine.{{ base_domain }}/authentication/idp/metadata

##
# VM config for the api app
##
api:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"
  janus:
    user: engineblock
    secret: ACAvoLNeelXDm7dPwY5Lw-N_GUFAQWDIqiBQs-XeG2-Gbu54UNiW_jUrK_uBVzCU8yyyieAJbRJY
    uri: https://serviceregistry.{{ base_domain }}/simplesaml/module.php/janus/services/rest/
  jdbc:
    user: apirw
    url: jdbc:mysql://localhost:3306/api
    password: ACAvoLNeelXDm7dPwY5Lw-N_GUFAQWDIqiBQs-XeG2-Gbu54UNiW_jUrK_uBVzCU8yyyieAJbRJY
  ldap:
    url: ldap://ldap.{{ base_domain }}:389
    userDn: "cn=engine,dc=surfconext,dc=nl"
    password: ACAvoLNeelXDm7dPwY5Lw-N_GUFAQWDIqiBQs-XeG2-Gbu54UNiW_jUrK_uBVzCU8yyyieAJbRJY
  engineblock:
    user: "{{ engine_database_user }}"
    url: jdbc:mysql://{{ engine_database_host }}:3306/{{ engine_database_name }}
    password: "{{ engine_database_password }}"
  teams:
    user: teamsrw
    url: jdbc:mysql://localhost:3306/teams
    password: ACAvoLNsq2VCDZAEwUldTSn2waM9mIazqxmykoTbpZQaPuIV0ye_7YswiMFrTD1pbXE_UGBW2OTb
  oauth:
    callback_url: https://api.{{ base_domain }}/v1/test/oauth-callback.shtml
  staticContentBasePath: https://static.{{ base_domain }}
  saml:
    entityId: https://api.{{ base_domain }}/
    assertionConsumerURI: https://api.{{ base_domain }}/v1/assertionConsumer
  ehcache:
    path: /tmp

##
# VM config for the grouper app
##
grouper:
  teams_db_user: teamsrw
  teams_db_host: localhost
  teams_db_password: ACAvoLNsq2VCDZAEwUldTSn2waM9mIazqxmykoTbpZQaPuIV0ye_7YswiMFrTD1pbXE_UGBW2OTb

ldap_user: cn=ro,dc=surfconext,dc=nl
ldap_password: ACAvoLMUTPe1xi6rIcz1QW8DaphUZBK2dLDQ-ixuuZk97skQxPLVio2zbJdLI8vQPMqQYcKj40cS
ldap_grouper_unit_test_user: gadget
ldap_grouper_engine_user: engine
ldap_grouper_api_user: api

##
# VM config for the apis app
##
apis:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"
  user: apisrw
  url: jdbc:mysql://localhost:3306/apis
  password: ACAvoLN6NUIXOTcZw5OanCDn6Wty1faR_yBbD-0-8geX_quSqEp6Gk8RFIpVmDBymndqn7iCoOzh
  entity_id: https://apis.{{ base_domain }}
  group_name: urn:collab:group:test.surfteams.nl:nl:surfnet:diensten:managementvo
  admin_service:
    resource_server_key: authorization-server-admin
    resource_server_secret: ACAvoLN9oE35zmjam6Z5athj5Gf_vJV65O1sjNhbcpEsMubNd5CpRxNk7zWSrqLkJtYAgG-4fvCo7vxXug8MSIKOZVrrBZiNks916eh_McBLcXZrpf6vFb8
  api:
    consumer_key: https://apis.test.surfconext.nl
    consumer_secret: ACAvoLMx3F7lC4ypJrDqyls4Iu4XHMtzUNUT7ihcMeCZkJx9q7M2DiLzWiNqM46k5zh-mrg5wrhM2vK4Eq-8o-lamCjBajx8sQ

mujina:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"
