---
engine:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"

profile:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"


engine_janus_secret: ACAvoLMrTw8Azpw2Ml3c9nbivbvyQchg9zQ2ShwViJOxT9eqeI-e79xLYpKgN4xGsT_GzBGXWlDYDxWw63WvDAZyvamP_46DGg
engine_janus_cache_lifetime: 0

engine_vovalidate_key : oauth_key
engine_vovalidate_secret : ACAvoLPlQEX-b0RMc52JY5o0qtYuLA8lT2pJ9TaIZQymmRAuXYysq7oxmPDSXN9cGUgKnWXdhA0ZWvQZWtFm2qEFBBeXf_pUxQ

engine_trusted_proxy_ips:
  - 192.168.1.1
  - 10.0.0.1
#
engine_keys:
  default:
    privateKey: engineblock.pem.encrypted
    privateFile: /etc/openconext/engineblock.pem
    publicKey: engineblock.crt
    publicFile: /etc/openconext/engineblock.crt

engine_initial_sql: "engineblock.sql"

#janus_ssp_title_suffix: SURFConext TEST
#
#janus_database_password: AFc_w24hvQMxivA6g2Eykp8CKVqwr1HnQJgCiwEiG6crkCp0YyX2qS7hMTAQ3BWqqff9hvAzdT9D
