---
env: vm
apache_server_admin: unix@prolocation.net

janus_ssp_technicalcontact_name: "Surfconext beheer"
janus_ssp_technicalcontact_email: "surfconext-beheer@surfnet.nl"
janus_ssp_managingcontact_name: "Surfconext beheer"
janus_ssp_managingcontact_email: "surfconext-beheer@surfnet.nl"


engine_idp_debugging_email_address: coin-logs-dev@list.surfnet.nl

# when using multiple certificates list them all (and their bundles) under tls.certificates
tls:
  cert_path: /etc/pki/tls/certs
  cert_private_path: /etc/pki/tls/private
  certificates:
    - "{{ tls_https.crt_name }}"
    - "{{ tls_https.bundle_name }}"
  private_keys:
    - "{{ tls_https.key_name }}"


engine_database_name: eb
engine_database_host: db.{{ base_domain }}
engine_database_user: ebrw
engine_database_password: ACAvoLNeelXDm7dPwY5Lw-N_GUFAQWDIqiBQs-XeG2-Gbu54UNiW_jUrK_uBVzCU8yyyieAJbRJY

engine_ldap_host: ldap.{{ base_domain }}
engine_ldap_bind_dn: "cn=engine,dc=surfconext,dc=nl"
engine_ldap_password: ACAvoLM9A__9zpR5wmn-7zJSji8f7i4Jnl9vxvgc7yY18mZShQ_0_djlglxdGhc6iFctRiQlv5KK

janus_database_name: sr
janus_database_host: db.{{ base_domain }}
janus_database_user: srrw
janus_database_password: ACAvoLO-pSK11LiWuOVsTljviCISlTdmJpJMNGb0iIDNwljUrIPcP_3ANoK-59FU86o-g0XsLV2VKcLX2Gjwkh97wF6JW1xvDw


# the welcome page on: vm.{{ base_domain }}
welcome:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"
