---
env: vm
env_name: java-{{ env }}
base_domain: "{{ env }}.openconext.org"

tls_https:
  key_name: star.{{ base_domain }}.key
  crt_name: star.{{ base_domain }}.pem
  bundle_name: star.{{ base_domain }}_ca_bundle.pem

tls:
  cert_path: /etc/pki/tls/certs
  cert_private_path: /etc/pki/tls/private
  certificates:
    - "{{ tls_https.crt_name }}"
    - "{{ tls_https.bundle_name }}"
  private_keys:
    - "{{ tls_https.key_name }}"


# shibboleth
shibboleth_apps:
  - teams
shib:
  engine_domain: "{{ base_domain }}"


# tomcat
keystore_password: ACAvoLNaJSARHx9BSmUpockTtDLp_LSmx9DkGnvuk62VtREBsK_IRVr1MM9AAsbb__Xsc4pp5YPa

# mysql
mysql_root_password: ACAvoLMFVoLhAysoj9JUJ0FmyQWRLzUUaDVEuESVwnpA8rtUyZtY3ZMofYPy4DFaZnzXWFjx_1hY
databases:
  names:
    - teams
    - api
  users:
    - { name: teamsrw, db_name: teams, password: ACAvoLNsq2VCDZAEwUldTSn2waM9mIazqxmykoTbpZQaPuIV0ye_7YswiMFrTD1pbXE_UGBW2OTb }
    - { name: apirw, db_name: api, password: ACAvoLNeelXDm7dPwY5Lw-N_GUFAQWDIqiBQs-XeG2-Gbu54UNiW_jUrK_uBVzCU8yyyieAJbRJY }

# versions of installed apps
teams_version: 4.0.6
#teams_snapshot_timestamp: 20141112.081923-4

api_version: 4.0.1
api_snapshot_timestamp: 20150115.230128-349

# teams
teams:
  team_db_password: ACAvoLNsq2VCDZAEwUldTSn2waM9mIazqxmykoTbpZQaPuIV0ye_7YswiMFrTD1pbXE_UGBW2OTb
  team_db_host: localhost
  eb_db_password: ACAvoLPY26q3FD4KZkXCJtWpQi7GW10qpS8LgW5IEDGherQr8yv5KDlCpdYoyZ8Qts28kfvFdRxm
  eb_db_host: db.{{ base_domain }}
  mail_server: localhost
  group_name_context: "urn:collab:group:test.surfteams.nl:"

#api
api:
  janus:
    user: engineblock
    secret: ACAvoLNeelXDm7dPwY5Lw-N_GUFAQWDIqiBQs-XeG2-Gbu54UNiW_jUrK_uBVzCU8yyyieAJbRJY
    uri: https://serviceregistry.{{ base_domain }}/simplesaml/module.php/janus/services/rest/
  jdbc:
    user: apirw
    url: jdbc:mysql://localhost:3306/api
    password: ACAvoLNeelXDm7dPwY5Lw-N_GUFAQWDIqiBQs-XeG2-Gbu54UNiW_jUrK_uBVzCU8yyyieAJbRJY
  ldap:
    url: ldap://ldap.{{ base_domain }}:389
    userDn: "cn=engine,dc=surfconext,dc=nl"
    password: ACAvoLNeelXDm7dPwY5Lw-N_GUFAQWDIqiBQs-XeG2-Gbu54UNiW_jUrK_uBVzCU8yyyieAJbRJY
  engineblock:
    user: ebrw
    url: jdbc:mysql://db.{{ base_domain }}:3306/eb
    password: ACAvoLNeelXDm7dPwY5Lw-N_GUFAQWDIqiBQs-XeG2-Gbu54UNiW_jUrK_uBVzCU8yyyieAJbRJY
  teams:
    user: teamsrw
    url: jdbc:mysql://localhost:3306/teams
    password: ACAvoLNsq2VCDZAEwUldTSn2waM9mIazqxmykoTbpZQaPuIV0ye_7YswiMFrTD1pbXE_UGBW2OTb
  oauth:
    callback_url: https://api.{{ base_domain }}/v1/test/oauth-callback.shtml
  staticContentBasePath: https://static.{{ base_domain }}
  saml:
    entityId: https://api.{{ base_domain }}/
    assertionConsumerURI: https://api.{{ base_domain }}/v1/assertionConsumer
    idpUrl: https://engine.{{ base_domain }}/authentication/idp/single-sign-on
    idpEntityId: https://engine.{{ base_domain }}/authentication/idp/metadata
  ehcache:
    path: /tmp

