---
env: test
base_domain: test2.surfconext.nl
db_host: db.test.surfconext.nl
ldap_host: ldap.test.surfconext.nl:389

# on the VM we use the same certificate for all domains under base_domain.
tls_https:
  key_name: star.{{ base_domain }}.key
  crt_name: star.{{ base_domain }}.pem
  bundle_name: star.{{ base_domain }}_ca_bundle.pem

apache_server_admin: unix@prolocation.net

janus_ssp_technicalcontact_name: "Surfconext beheer"
janus_ssp_technicalcontact_email: "surfconext-beheer@surfnet.nl"
janus_ssp_managingcontact_name: "Surfconext beheer"
janus_ssp_managingcontact_email: "surfconext-beheer@surfnet.nl"

janus_ssp_auth_admin_password: AO389jIzP7vzelkU_EIOSaKzfy6nldVti3WHcfnlLTJ4xjxcOOcclhj5OOMkur0PkCkhl04b5kK4
janus_ssp_secretsalt: AO389jLCxf-3SVaII3ZhDTpTIfKM4xjfN8WOVBHjsOgnNKyGRz7i0cfNfhf2SC6VWACXm49ul91ychZNV8kjougnPayHMjoNlw

engine_idp_debugging_email_address: coin-logs-dev@list.surfnet.nl

# when using multiple certificates list them all (and their bundles) under tls.certificates
tls:
  cert_path: /etc/pki/tls/certs
  cert_private_path: /etc/pki/tls/private
  certificates:
    - "{{ tls_https.crt_name }}"
    - "{{ tls_https.bundle_name }}"
  private_keys:
    - "{{ tls_https.key_name }}"

engine_janus_user: engineblock
engine_janus_secret: AO389jK0DeSFenU_V0tqOaemIpi9C3hV5i7cpT4l31fT2FlXA_rK9rQZJa7EELhtzB_iycPYsUoV

engine_database_name: eb
engine_database_host: "{{ db_host }}"
engine_database_user: ebrw
engine_database_password: AO389jIHbuH1WELmGAVexwynvtNwSyFI1EABj5YxOpULMvMTc3KnJLnfxXWvzztb2XtVRDUT_9Yp

engine_ldap_host: ldap.{{ base_domain }}
engine_ldap_bind_dn: "cn=engine,dc=surfconext,dc=nl"
engine_ldap_password: AO389jIRf1SzuFY6TuyVNO2bZyRSNCT6K9r54IEDRLSENhWz1fa_jRqMQ1qNhYC9ARRs3pyiSRs1

engine_api_janus_password: AO389jIDumapQeFtN7yFSUd2imW4bbXWp2-njpLQy4-d7Y0YuoJCw7a7GvbaZ0AP_25uEZkEsBGn


ldap_password: "{{ engine_ldap_password }}"
ldap_grouper_unit_test_user: gadget

janus_database_name: sr
janus_database_host: "{{ db_host }}"
janus_database_user: srrw
janus_database_password: AO389jJqUoyI5aGSB600-4b-iJws-pvjzRT_K4CLpZ8WG-BhtdYOHdU8jcJZdfqODccCsrI96kL_

# host for static files (IdP logos)
static:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"

# the welcome page on: vm.{{ base_domain }}
welcome:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"


janus_teams_oauth_key: https://teams.test.surfconext.nl/teams/teams.xml
janus_teams_oauth_secret: AO389jJd20OzMwKw4E5vvzQiC5DyO59_KddmGx93CCLwvFFKq6JZa-Ks2m4cCN3tUzdeD_36qJpa

engine:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"

profile:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"

janus:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"

engine_janus_cache_lifetime: 0

engine_vovalidate_key : oauth_key
engine_vovalidate_secret : AO389jKTQb-djeNNsd7w2Mp5XP1322VfzoGc2aoMLf_5wCN6jaajPggty3eCVPlimh_wqYOjzvvU

engine_trusted_proxy_ips:
  - 192.168.1.1
  - 10.0.0.1
#
engine_keys:
  default:
    privateKey: engineblock.pem.encrypted
    privateFile: /etc/openconext/engineblock.pem
    publicKey: engineblock.crt
    publicFile: /etc/openconext/engineblock.crt


tomcat_apps:
  - api
  - teams
  - grouper
  - mujina-sp
  - mujina-idp

# shibboleth
shibboleth_apps:
  teams:
    entityID: "https://teams.{{ base_domain }}/shibboleth"
    baseurl: ""
  grouper:
    entityID: "https://grouper.{{ base_domain }}/grouper/shibboleth"
    baseurl: "/grouper"
  authz:
    entityID: "https://authz.{{ base_domain }}/shibboleth"
    baseurl: ""
  "authz-admin":
    entityID: "https://authz-admin.{{ base_domain }}/shibboleth"
    baseurl: ""
shib:
  engine_domain: "{{ base_domain }}"

# tomcat
keystore_password: AO389jIasT77KXigYsv1RmA_BhnBl1JtgS_LNXx9nX_zidPPx8K9w70OAHNp2joMffSJmedtyE12

# versions of installed apps
teams_version: 4.0.7
teams_snapshot_timestamp: 20150205.105251-3

api_version: 4.0.1
api_snapshot_timestamp: 20150302.230045-395

mujina_version: 4.0.2
#mujina_snapshot_timestamp

##
# VM config for the teams app
##
teams:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"
  team_db_password: AO389jKA2AnwgW79TARlzVETaDfwjRv5vUf3PjuqnlEq7WRkpZwhmBeUom4hrWCyoylI3rdoMXP9fVnczW_rFyX4tXmwpTqSDg
  team_db_host: "{{ db_host }}"
  eb_db_password: AO389jLFjCMf3dxInL1kB1P2RZB_-t7q8_qxzP1MbhWicU5L3wlsXPcbB1DL5N9AgD-rX2lRBkle
  eb_db_host: "{{ db_host }}"
  mail_server: s01.dev.coin.surf.net
  group_name_context: "urn:collab:group:test.surfteams.nl:"

engineblock:
  idp_url: https://engine.{{ base_domain }}/authentication/idp/single-sign-on
  idp_entity_id: https://engine.{{ base_domain }}/authentication/idp/metadata

##
# VM config for the api app
##
api:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"
  janus:
    user: "{{ engine_janus_user }}"
    secret: "{{ engine_janus_secret }}"
    uri: https://serviceregistry.{{ base_domain }}/simplesaml/module.php/janus/services/rest/
  jdbc:
    user: apirw
    url: "jdbc:mysql://{{ db_host }}/api"
    password: AO389jJKrY50bkZw2-cer1PEcza8evQegVMXZ3LYibPNFnIdAGP3eTflbK9ijICL3Rb1xD1_Xcw9EgwzHDKKbR6BV44O9LT9Ow
  ldap:
    url: ldap://ldap.{{ base_domain }}:389
    userDn: "{{ engine_ldap_bind_dn }}"
    password: "{{ engine_ldap_password }}"
  engineblock:
    user: "{{ engine_database_user }}"
    url: jdbc:mysql://{{ engine_database_host }}:3306/{{ engine_database_name }}
    password: "{{ engine_database_password }}"
  teams:
    user: teamsrw
    url: "jdbc:mysql://{{ db_host }}/teams"
    password: "{{ teams.team_db_password }}"
  oauth:
    callback_url: https://api.{{ base_domain }}/v1/test/oauth-callback.shtml
  staticContentBasePath: https://static.{{ base_domain }}
  saml:
    entityId: https://api.{{ base_domain }}/
    assertionConsumerURI: https://api.{{ base_domain }}/v1/assertionConsumer
  ehcache:
    path: /tmp

##
# VM config for the grouper app
##
grouper:
  db_user: grouperrw
  db_host: "{{ db_host }}"
  db_password: AO389jJ9IITviA1aIY-FCk-7OaSKYeT0_BEpDt1BucM4JN1H9Q0vFWWneYDpR11JJOuZ9cmzwqLqC6GNRV9_W3TCp8lLUMikqQ
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"


ldap_user: cn=ro,dc=surfconext,dc=nl
ldap_grouper_engine_user: engine

##
# VM config for the apis app
##
apis:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"
  user: apisrw
  url: "jdbc:mysql://{{ db_host }}/apis"
  password: AO389jK__uubzomGDJ860wSViZfWGnB4QQgy_bYjHZqAUeF3UzsXSF9WsobT5xj9D7onqcaSJ8m4
  entity_id: https://apis.{{ base_domain }}
  group_name: urn:collab:group:test.surfteams.nl:nl:surfnet:diensten:managementvo
  admin_service:
    resource_server_key: authorization-server-admin
    resource_server_secret: AO389jIbwPB83bw9a_btPOrSjpRqK5nWFargxnnwRYINnkEUbGa1uAJF93b0NlkKgK-Rk99XGnByCustw7Lfo-nl-u8nTSONZQQ0XSgo5u5Wj7TI7orNVhA
  api:
    consumer_key: https://apis.test.surfconext.nl
    consumer_secret: AO389jJoZ2JEVK1Bgk0RBCfPjAa3Jxv6iCBtLqZbjGh6zIrhgIegBCI7-rjfzE4pUVzZit1pgLKyY33nNktzOhtLzJSO0osL3Q

mujina:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"


tomcat_grouper_password: AO389jLvTEwDbIPGyG8wxULmFuEFYlwSqQlRn8Ec3LCHumPMnB3Conq8gNKgPaddDCedI7Z9j7ya

##
# VM config for the Authorization Server
##
authzserver:
  db_user: authz-serverrw
  db_password: AO389jIKSnsfbVwnpm3At8jnZF_LjR3iThzteQAHQTJZsggoMZJyOTpix__B6W8D7DJyriTJLLQg
  db_host: "{{ db_host }}"
  db_name: authz-server
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"

authz_server_version: 1
authz_server_snapshot_timestamp: 20150316.120118-42

##
# VM config for the Voot app
##
voot:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"
  resource_checking_secret: AO389jIK6VOa_Ec7KX8rXicWpot5eN2cpxg0Ztrt18snMhuRJOgQvNae5XvMjHvlGG11Jj8-1NF6
  externalGroupProviders:
    - {
        type: "grouper",
        url: "https://grouper.vm.openconext.org/grouper-ws/services/GrouperService_v2_0",
        credentials: {
          username: "gadget",
          secret: "{{ tomcat_grouper_password }}"
        },
        schacHomeOrganization: "surfnet.nl",
        timeoutMillis: 3000
      }
voot_version: 1
voot_snapshot_timestamp: 20150316.152804-27

##
# VM config for the authz-admin application
##
authz_admin_version: 1
authz_admin_snapshot_timestamp: 20150316.153010-41
authz_admin_client_secret: AO389jJRzD0PhvfTkJQAeAXxzpCLhPhegalI2g8srABF2YyB2977dZ2R3PmbJnP8kv1QkmzCYXjo
authzadmin:
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"
  defaultClients:
      - clientId: "{{ authzplayground.springapp_client_id}}"
        secret: "{{ authzplayground.springapp_client_secret }}"
        resourceIds:
          - groups
        scopes:
          - read
        grantTypes:
          - authorization_code
          - implicit
        redirectUri: "{{ authzplayground.springapp_oauth_redirect }}"
      - clientId: authz-admin-vm
        secret: "{{ authz_admin_client_secret }}"
        resourceIds:
          - groups
        scopes:
          - groups
        grantTypes:
          - authorization_code
        redirectUri: https://authz-admin.{{ base_domain }}
  defaultResourceServers:
    - clientId: vootservice
      secret: "{{ voot.resource_checking_secret }}"
##
# VM config for the authz-admin application
##
authz_playground_version: 1
authz_playground_snapshot_timestamp: 20150316.120215-11
authzplayground:
  springapp_oauth_redirect: https://authz-playground.{{ base_domain }}/redirect
  springapp_oauth_token_url: https://authz.{{ base_domain }}/oauth/token
  springapp_client_id: cool_app_id
  springapp_client_secret: AO389jJSpbD_GNIAAPRFbDTXJuwN9lInCRbeqwpi_qJhYF0QOTbvrpllfpE9ufi6PIBVe04t02ku
  springapp_authorize_url: https://authz.{{ base_domain }}/oauth/authorize
  springapp_resource_server_api_url: https://voot.{{ base_domain }}/me/groups
  crt_name: "{{ tls_https.crt_name }}"
  key_name: "{{ tls_https.key_name }}"
  bundle_name: "{{ tls_https.bundle_name }}"
