---
- name: copy templates
  template: src={{ item }}.j2 dest={{ tomcat.install_dir }}/{{ tomcat.properties_dir }}/{{ item }}
  with_items:
    - grouper.hibernate.properties
    - sources.xml
  notify: restart tomcat
  tags:
    - grouper


- name: copy files
  copy: src={{ item }} dest={{ tomcat.install_dir }}/{{ tomcat.properties_dir }}/{{ item }}
  with_items:
    - grouper.properties
    - log4j.properties
  notify: restart tomcat
  tags:
    - grouper

- name: get grouper shell
  get_url:
    url: https://build.surfconext.nl/repository/public/third-party/edu/internet2/grouper/release/2.1.5/grouper.apiBinary-2.1.5.tar.gz
    dest: ~/grouper.apiBinary-2.1.5.tar.gz
  tags:
    - grouper

- name: create /opt/www
  file: path=/opt/www state=directory
  tags:
    - grouper

- name: extract grouper shell
  unarchive: src=~/grouper.apiBinary-2.1.5.tar.gz dest=/opt/www copy=no creates=/opt/www/grouper.apiBinary-2.1.5
  tags:
    - grouper

- name: use correct grouper config
  template: src={{ item.src }}.j2 dest=/opt/www/grouper.apiBinary-2.1.5/conf/{{ item.dest }}
  tags: grouper
  with_items:
    - { src: grouper-shell.hibernate.properties, dest: grouper.hibernate.properties }
    - { src: sources.xml, dest: sources.xml }

- name: correct values for grouper.properties
  lineinfile: dest=/opt/www/grouper.apiBinary-2.1.5/conf/grouper.properties regexp=^{{ item.line }} line={{ item.line }}={{ item.value }}
  with_items:
    - { line: configuration.autocreate.system.groups, value: true}
    - { line: groups.wheel.use, value: true}
  tags: grouper

- name: create symlink to current
  file: src=/opt/www/grouper.apiBinary-2.1.5 dest=/opt/www/grouper-shell state=link
  tags: grouper

- name: initialize grouper
  shell: bin/gsh -registry -runscript -noprompt
  changed_when: False # this will always report a change... so "sudo be quiet"...
  args:
    chdir: /opt/www/grouper-shell
  tags: grouper

#TODO: This is probably only in vm?
#- name: copy ldap provision for mujina
#  copy: src={{ item }} dest=~/{{ item }}
#  with_items:
#    - provision-ldap.gsh
#  tags: grouper

#TODO: This is probably only in vm?
#- name: provision ldap for mujina
#  shell: bin/gsh ~/provision-ldap.gsh
#  args:
#    chdir: /opt/www/grouper-shell
#  tags: grouper

