---
diyidp_fpm_user: diyidp
simplesamlphp_version: 1.14.9
diyidp_current_release_symlink: "{{ openconext_releases_dir }}/OpenConext-diyidp"
diyidp_domain: diyidp."{{ base_domain }}"
diyidp_cert: "diyidp.crt"

diyidp:
  db_host: "{{ mysql_host }}"
  db_name: diyidp
  db_user: diyidprw
  dp_password: "{{ mysql_passwords.diyidp }}"
diyidp_remotesp:
  - name: "{{ instance_name }} SP metadata"
    metadataurl: "https://engine.{{ base_domain }}/authentication/sp/metadata"
    acslocation: "https://engine.{{ base_domain }}/authentication/sp/consume-assertion"

