sudo: required

services:
  - docker

before_install:
- sudo docker build -t surfnet/centos7-openconext -f tests/Dockerfile.centos-7 .

script:
  - sudo docker run --rm -t surfnet/centos7-openconext

