sudo: required

services:
  - docker

before_install:
  - sudo docker build --rm -t surfnet/centos7-openconext -f tests/Dockerfile.centos-7 .

script:
  - sudo docker run --detach -v "${PWD}":/ansible:rw -v /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged --name ansible-test surfnet/centos7-openconext
  - >
    sudo docker exec -t ansible-test env TERM=xterm
    ansible-playbook -i /ansible/environments/docker/inventory /ansible/provision-docker.yml
    -e secrets_file=/ansible/environments/vm/secrets/vm.yml
    --syntax-check
  - >
    sudo docker exec -t ansible-test env TERM=xterm
    ansible-playbook -i /ansible/environments/docker/inventory /ansible/provision-docker.yml
    -e secrets_file=/ansible/environments/vm/secrets/vm.yml
  - >
    sudo docker exec -t ansible-test
    ansible-playbook /ansible/environments/docker/inventory /ansible/provision-docker.yml
    -e secrets_file=/ansible/environments/vm/secrets/vm.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - sudo docker stop ansible-test

