sudo: required

services:
  - docker

before_install:
  - sudo docker build --rm -t surfnet/centos7-openconext -f tests/Dockerfile.centos-7 .

script:
  - sudo docker run --detach -v "${PWD}":/ansible:ro -v /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged --name java-apps surfnet/centos7-openconext
  - sudo docker exec -t java-apps env TERM=xterm ansible-playbook -i /ansible/environments/docker/inventory /ansible/provision-docker.yml -e secrets_file=/ansible/environments/vm/secrets/vm.yml --syntax-check
  - sudo docker exec -t java-apps env TERM=xterm ansible-playbook -i /ansible/environments/docker/inventory /ansible/provision-docker.yml -e secrets_file=/ansible/environments/vm/secrets/vm.yml
  - sudo docker stop java-apps

