sudo: required

services:
  - docker

before_install:
  - sudo docker build --rm -t surfnet/centos7-openconext -f tests/Dockerfile.centos-7 .

script:
  - sudo /bin/bash ./tests/travis-build.sh

after_failure:
  - sudo docker exec -t ansible-test yum install -y net-tools
  - sudo docker exec -t ansible-test netstat -apn
  - sudo docker exec -t ansible-test systemctl status -l haproxy
  - sudo docker exec -t ansible-test systemctl status -l httpd
  - sudo docker exec -t ansible-test systemctl status metadata-exporter.service
  - sudo docker exec -t ansible-test systemctl status teams.service
  - sudo docker exec -t ansible-test cat /var/log/teams/teams.log
  - sudo docker exec -t ansible-test ls -ltr /var/log
  - sudo docker exec -t ansible-test cat /var/log/metadata-exporter/metadata-exporter.log
  - sudo docker exec -t ansible-test cat /var/log/voot/voot.log
  - sudo docker exec -t ansible-test cat /var/log/pdp/pdp.log
  - sudo docker exec -t ansible-test env TERM=xterm tail -500 /var/log/messages

after_script:
  - sudo docker stop ansible-test

