sudo: required

services:
  - docker

before_install:
  - sudo docker build --rm -t surfnet/centos7-openconext -f tests/Dockerfile.centos-7 .

script:
  - sudo docker run --detach -v "${PWD}":/ansible:ro -v /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged --name ansible-test surfnet/centos7-openconext
  - sudo docker exec -t ansible-test env TERM=xterm ansible-playbook -i /ansible/inventory/docker /ansible/provision-docker.yml -e secrets_file=/ansible/secrets/vm.yml --syntax-check
  - sudo docker exec -t ansible-test env TERM=xterm ansible-playbook -i /ansible/inventory/docker /ansible/provision-docker.yml -e secrets_file=/ansible/secrets/vm.yml
  - sudo docker stop ansible-test

