---
- hosts: php-apps
  sudo: yes
  gather_facts: no
  vars:
    env_lang: php
  roles:
    - php
    - static
    - { role: openconext-common, tags: ['eb','sr']}
    - { role: openconext-engineblock, tags: ['eb'] }
    - { role: janus, tags: ['sr'] }
