---

- hosts: openconext-java
  sudo: true
  vars:
    env_lang: java
  roles:
    - common
    - tls
    - httpd
    - tomcat
    - java
    - { role: shibboleth, tags: ['shib'] }
    - grouper
    - teams
    - api
    - apis
    - { role: authz-server, tags: ['authz'] }
    - voot
