---

- hosts: openconext-java
  sudo: true
  roles:
    - common
    - {role: generate_certs, when: env_name == "java-vm" }
    - httpd
    - tomcat
    - java
    - {role: mysql, when: env_name == "java-vm" }
    - {role: hosts, when: env_name == "java-vm" }
    - shibboleth
    - teams
