---

- hosts: openconext-java
  sudo: true
  vars:
    env_lang: java
  roles:
    - common
    - tls
    - httpd
    - tomcat
    - java
    - { role: shibboleth, tags: ['shib'] }
    - grouper
    - teams
    - api
    - apis
    - { role: authz-server, tags: ['oauth', 'authz'] }
    - { role: authz-admin, tags: ['oauth', 'authz-admin'] }
    - { role: authz-playground, tags: ['oauth', 'authz-playground'] }
    - { role: voot, tags: ['oauth', 'voot'] }
