---
- hosts: all
  gather_facts: no
  tasks:
  - name: Read vars from secrets file
    include_vars: "{{ secrets_file }}"
    tags:
      - always

- hosts: loadbalancer:php-apps:java-apps:storage:oidc:dbcluster
  gather_facts: yes
  become: true
  roles:
    - { role: common,   tags: ['common'] }
    - { role: users,   tags: ['users'] }
    - { role: tls,      tags: ['tls'] }
    - { role: iptables,      tags: ['iptables'] }
    - { role: rsyslog,      tags: ['rsyslog'] }
  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: loadbalancer
  gather_facts: true
  become: true
  roles:
    - { role: keepalived, tags: ['keepalived'] }
    - { role: haproxy, tags: ['lb'] }
    - { role: bind, tags: ['bind'] }

- hosts: php-apps:java-apps:oidc
  gather_facts: no
  become: true
  roles:
    - { role: httpd,     tags: ['httpd'] }
  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: storage
  gather_facts: no
  become: true
  roles:
    - { role: mysql, tags: ['mysql'] }
    - { role: ldap,  tags: ['ldap' ] }

- hosts: dbcluster
  gather_facts: yes
  become: true
  roles:
    - { role: galera, tags: ['galera'] }
      
- hosts: php-apps
  gather_facts: no
  become: true
  vars:
    env_lang: php
  roles:
    - { role: php56fpm,          tags: ['php'     ] }
    - { role: static,            tags: ['static'  ] }
    - { role: openconext-common, tags: ['eb5','sr','profile'] }
    - { role: engineblock5,      tags: ['eb5'     ] }
    - { role: janus,             tags: ['sr'      ] }
    - { role: profile,           tags: ['profile' ] }
  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: java-apps
  gather_facts: true
  become: true
  vars:
    env_lang: java
  roles:
    - { role: tomcat,           tags: ['tomcat' ] }
    - { role: java,             tags: ['java' ] }
    - { role: shibboleth,       tags: ['shib'   ] }
  handlers:
    - include: roles/httpd/handlers/main.yml
      
- hosts: java-apps
  gather_facts: true
  become: true
  vars:
    env_lang: java
  roles:
    - { role: mujina-idp,       tags: ['mujina' ] }
    - { role: mujina-sp,        tags: ['mujina' ] }
    - { role: grouper,          tags: ['grouper'] }
    - { role: teams,            tags: ['teams'  ] }
    - { role: authz-server,     tags: ['oauth', 'authz-server'    ] }
    - { role: authz-admin,      tags: ['oauth', 'authz-admin'     ] }
    - { role: voot,             tags: ['oauth', 'voot'            ] }
    - { role: authz-playground, tags: ['oauth', 'authz-playground'] }
    - { role: pdp,              tags: ['pdp'] }
    - { role: metadata-exporter, tags: ['metadata-exporter']}

  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: oidc
  gather_facts: true
  become: true
  vars:
    env_lang: java
  roles:
    - { role: oidc,            tags: ['oidc' ] }
  handlers:
    - include: roles/httpd/handlers/main.yml
    - include: roles/tomcat/handlers/main.yml
