---
- hosts: all
  gather_facts: no
  tasks:
  - name: Read vars from secrets file
    include_vars: "{{ secrets_file }}"
    tags:
      - always

- hosts: all
  gather_facts: yes
  become: true
  roles:
    - { role: common, tags: ['common'] }
    - { role: iptables, tags: ['iptables'] }
  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: loadbalancer
  gather_facts: no
  become: true
  roles:
    - { role: haproxy, tags: ['lb'] }
    - { role: tls, tags: ['tls'] }

- hosts: php-apps:java-apps-centos7
  gather_facts: yes
  become: true
  roles:
    - httpd
  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: storage
  gather_facts: yes
  become: true
  roles:
    - { role: mysql, tags: ['mysql'] }
    - { role: ldap,  tags: ['ldap' ] }

- hosts: php-apps
  gather_facts: yes
  become: true
  vars:
    env_lang: php
  roles:
    - { role: php56fpm,          tags: ['php56fpm'] }
    - { role: static,            tags: ['static'] }
    - { role: openconext-common, tags: ['eb5','sr'] }
    - { role: engineblock5,       tags: ['eb5'     ] }
    - { role: janus,             tags: ['sr'     ] }
  handlers:
    - include: roles/httpd/handlers/main.yml

- hosts: java-apps-centos7
  gather_facts: true
  become: true
  vars:
    env_lang: java
  roles:
    - { role: tomcat, tags: ['tomcat'] }
    - { role: java,   tags: ['java'] }
    - { role: shibboleth,        tags: ['shib'   ] }
    - { role: grouper,           tags: ['grouper'] }
    - { role: metadata-exporter, tags: ['metadata-exporter'] }
    - { role: teams,             tags: ['teams'  ] }
    - { role: mujina-idp,        tags: ['legacy' ] }
    - { role: mujina-sp,         tags: ['legacy' ] }
    - { role: authz-server,      tags: ['oauth', 'authz-server'    ] }
    - { role: authz-admin,       tags: ['oauth', 'authz-admin'     ] }
    - { role: voot,              tags: ['oauth', 'voot'            ] }
    - { role: authz-playground,  tags: ['oauth', 'authz-playground'] }
    - { role: pdp,               tags: ['pdp'] }
    - { role: oidc,              tags: ['oidc'] }
    - { role: aa,                tags: ['aa'] }
    - { role: pdp,               tags: ['pdp'] }
    - { role: attribute-mapper,  tags: ['attribute-mapper'] }
    - { role: eduproxy,          tags: ['eduproxy'] }
  handlers:
    - include: roles/httpd/handlers/main.yml
