---
- hosts: all
  gather_facts: no
  tasks:
  - name: Read vars from secrets file
    include_vars: "{{ secrets_file }}"
    tags:
      - always

- hosts: all
  gather_facts: yes
  sudo: true
  roles:
    - role: common
    - role: iptables
    - role: tls
  handlers:
    - include: roles/httpd/handlers/main.yml
    - include: roles/nginx/handlers/main.yml

- hosts: php-apps:java-apps-centos7
  gather_facts: yes
  sudo: true
  roles:
    - httpd
  handlers:
    - include: roles/httpd/handlers/main.yml
    - include: roles/nginx/handlers/main.yml

- hosts: java-apps-centos7
  gather_facts: true
  sudo: true
  vars:
    env_lang: java
  roles:
    - tomcat
    - java
    - shibboleth
    - metadata-exporter
    - grouper
    - teams
    - mujina-idp
    - mujina-sp
    - authz-server
    - voot
    - authz-playground
    - pdp
    - oidc
    - aa
  handlers:
    - include: roles/httpd/handlers/main.yml
    - include: roles/nginx/handlers/main.yml
