---
# TODO: API should package mysql in the war. But since we are going to replace it (eta 1/5/2015) we will leave it in for now...
- name: "DEPRECATED: copy the mysql jar into the shared/lib dir in tomcat."
  copy: src=mysql-connector-java-5.1.34.jar dest=/usr/share/tomcat6/shared/lib/mysql-connector-java-5.1.34.jar
  notify: restart tomcat

- name: copy over the api key
  copy: content="{{ lookup('file', 'files/' + env_name + '/certs/api_pkcs8.pem.encrypted') | vault }}" dest={{ tls.cert_private_path }}/api_pkcs8.pem
  tags:
    - api

- name: copy api certificate to correct location
  copy: src=files/{{ env_name }}/certs/api.crt dest={{ tls.cert_path }}/api.crt
  tags:
    - api

- name: register api key content
  shell: sed -e '1d;$d' {{ tls.cert_private_path }}/api_pkcs8.pem | tr -d '\n'
  register: api_key_content
  changed_when: False
  tags:
    - api

- name: register tls crt content
  shell: sed -e '1d;$d' {{ tls.cert_path }}/api.crt | tr -d '\n'
  register: api_crt_content
  changed_when: False
  tags:
    - api

- name: copy over the engineblock crt
  copy: src=files/php-{{ env }}/certs/engineblock.crt dest=~/engineblock.crt
  tags:
    - api

- name: register engineblock crt content
  shell: sed -e '1d;$d' ~/engineblock.crt | tr -d '\n'
  register: engineblock_crt_content
  changed_when: False
  tags:
    - api

- name: copy api configuration templates
  template: src={{ item }}.j2 dest=/etc/tomcat6/appconf/{{ item }}
  with_items:
    - coin-api.properties
    - api-ehcache.xml
  tags:
    - api
  notify: restart tomcat

- name: copy teams logging configuration
  copy: src=api-logback.xml dest=/etc/tomcat6/appconf/api-logback.xml group=tomcat owner=tomcat
  tags:
    - api
  notify: restart tomcat

- name: copy virtual host config
  template: src=api.conf.j2 dest=/etc/httpd/conf.d/api.conf
  tags:
    - api
  notify: restart httpd

