---
- name: Add Shibboleth repo
  copy: src={{ item }} dest=/etc/yum.repos.d/{{ item }}
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6") or
        (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  with_items:
    - shibboleth.repo
    - shibboleth.repo.gpgkey

- name: Add Shibboleth repo
  copy: src={{ item }} dest=/etc/yum.repos.d/{{ item }}
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  with_items:
    - shibboleth-centos7.repo
    - shibboleth.repo.gpgkey

- name: Install custom libcurl
  yum: name={{ item }} state=present
  with_items:
    - libcurl-openssl.x86_64

- name: Install
  yum: name={{ item }} state=present
  with_items:
    - shibboleth.x86_64

- name: Remove default conf files apache
  file: path=/etc/httpd/conf.d/{{ item }} state=absent
  with_items:
    - shib.conf

- name: Copy default config files
  copy: src={{ item }} dest=/etc/httpd/conf.d/20_shib.conf
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6") or
        (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  with_items:
    - 20_shib_apache22.conf
  notify: reload httpd

- name: Copy default config files
  copy: src={{ item }} dest=/etc/httpd/conf.d/20_shib.conf
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7") or
        (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  with_items:
    - 20_shib_apache24.conf
  notify: reload httpd

- name: Shibboleth config
  template: src=shibboleth/{{ item }}.j2 dest=/etc/shibboleth/{{ item }}
  with_items:
    - attribute-map.xml
    - localLogout.html
    - shibboleth2.xml
    - attribute-policy.xml
  notify:
    - restart shibd
    - reload httpd

- name: enable shibd
  service: name={{ item }} enabled=yes
  with_items:
    - shibd
  notify:
    - restart shibd
    - reload httpd
