---
- name: Create user
  user: name=authz-server home={{ authz_server_dir }}
  tags: authz-server

- name: Create logging directory
  file: path=/var/log/{{ java_app.name }} state=directory owner=authz-server group=authz-server mode=0755
  tags: authz-server

- name: Deploy | Download release
  get_url:
    url: "{{ maven_repo }}/org/openconext/authz-server/{{ authz_server_version }}/authz-server-{{ authz_server_version }}.jar"
    dest: "{{ authz_server_dir }}/{{ authz_server_jar }}"
    force: yes
  when: authz_server_snapshot_timestamp == '' and authz_server_local_jar == ''
  notify: restart authz-server
  tags: authz-server

- name: Deploy | Download snapshot
  get_url:
    url: "{{ maven_snapshot_repo }}/org/openconext/authz-server/{{ authz_server_version }}-SNAPSHOT/authz-server-{{ authz_server_version }}-{{ authz_server_snapshot_timestamp }}.jar"
    dest: "{{ authz_server_dir }}/{{ authz_server_jar }}"
    force: yes
  when: authz_server_snapshot_timestamp != '' and authz_server_local_jar == ''
  notify: restart authz-server
  tags: authz-server

- name: Deploy | Upload from local
  copy: src={{ authz_server_local_jar }} dest={{ authz_server_dir }}/{{ authz_server_jar }}
  when: authz_server_local_jar != ''
  notify: restart authz-server
  tags: authz-server

- name: Copy logging config
  template: src=logback.xml.j2 dest={{ authz_server_dir }}/logback.xml owner=authz-server group=authz-server mode=0740
  notify: restart authz-server
  tags: authz-server

- name: Copy application config
  template: src=application.properties.j2 dest={{ authz_server_dir }}/application.properties owner=authz-server group=authz-server mode=0740
  notify: restart authz-server
  tags: authz-server

- name: Copy start script
  template: src=templates/spring-boot.j2 dest=/etc/init.d/{{ java_app.name }} mode=0755
  notify: restart authz-server
  tags: authz-server
