---
- name: create user
  user: name=voot home={{ voot_dir }}
  tags: voot

- name: Deploying voot | Download release
  get_url:
    url: "{{ maven_repo }}/org/openconext/voot-service/{{ voot_version }}/voot-service-{{ voot_version }}.jar"
    dest: "{{ voot_dir }}/{{ voot_service_jar }}"
    force: yes
  when: voot_snapshot_timestamp == '' and voot_local_jar == ''
  tags: voot

- name: Deploying voot | Download snapshot
  get_url:
    url: "{{ maven_snapshot_repo }}/org/openconext/voot-service/{{ voot_version }}-SNAPSHOT/voot-service-{{ voot_version }}-{{ voot_version_timestamp }}.jar"
    dest: "{{ voot_dir }}/{{ voot_service_jar }}"
    force: yes
  when: voot_snapshot_timestamp != '' and voot_local_jar == ''
  tags: voot

- name: Deploying voot | Upload from local
  copy: src={{ voot_local_jar }} dest={{ voot_dir }}/{{ voot_service_jar }}
  when: voot_local_jar != ''
  tags: voot

- name: Copy logging config
  template: src=logback.xml.j2 dest={{ voot_dir }}/logback.xml owner=voot group=voot mode=0740
  tags: voot

- name: Copy application config
  template: src=application.properties.j2 dest={{ voot_dir }}/application.properties owner=voot group=voot mode=0740
  tags: voot

- name: Create logging directory
  file: path=/var/log/voot state=directory owner=voot group=voot mode=0755
  tags: voot

- name: Copy start script
  template: src=templates/spring-boot.j2 dest=/etc/init.d/{{ java_app.name }} mode=0755
  tags: voot

