springapp_artifact_id: authz-server
springapp_version: "{{ authz_server_version }}"
springapp_snapshot_timestamp: "{{ authz_server_snapshot_timestamp }}"
springapp_dir: "{{ authz_server_dir }}"
springapp_user: authz-server
springapp_service_name: authz-server
springapp_jar: "{{ authz_server_jar }}"
springapp_tcpport: 9190
