---
- name: Download current version
  get_url: url="{{ engine_download_url }}" dest="{{ engine_build_path }}"
  when: engine_branch == ''
  register: eb_download

- name: Unpack current version
  unarchive: src={{ engine_build_path }} dest={{ openconext_releases_dir }} copy=no
  when: engine_branch == '' and eb_download.changed

USE http://stackoverflow.com/questions/23014713/run-a-build-task-only-when-changes-have-been-pulled-from-a-git-repository

- name: Remove engine-block current release
  git: repo=https://github.com/OpenConext/OpenConext-engineblock.git dest="{{ openconext_releases_dir }}" version={{ engine_branch }}
  when: engine_branch != ''

- name: Checkout engine-block branch
  git: repo=https://github.com/OpenConext/OpenConext-engineblock.git dest="{{ openconext_releases_dir }}" version={{ engine_branch }}
  when: engine_branch != ''

- name: Install Apache vhost
  template: src={{ item }}.j2 dest=/etc/httpd/conf.d/{{ item }}
  with_items:
    - engine.conf
    - profile.conf
  notify:
    - restart httpd

- name: copy over the engineblock keys
  copy: content="{{ engineblock_private_key }}" dest={{ item.value.privateFile }}
  with_dict: engine_keys

- name: copy engineblock certificates to correct location
  copy: src=files/{{ env_name }}/certs/{{ item.value.publicKey }} dest={{ item.value.publicFile }}
  with_dict: engine_keys

- name: Configure EngineBlock
  template: src={{ item }}.j2 dest=/etc/openconext/{{ item }}
  with_items:
    - engineblock.ini

- name: Run EngineBlock migrations
  command: ./bin/migrate
  args:
    chdir: "{{ engine_release_dir }}"
  register: migrate_output
  changed_when: "'no update needed' not in migrate_output.stderr"

- name: Activate new EngineBlock
  file: src={{ engine_release_dir }} dest={{ engine_current_release_symlink }} state=link
  notify:
    - restart httpd

- name: import entries
  shell: ldapmodify -x -D cn=admin,cn=config -h {{ ldap_host }} -w {{ ldap_password }} -f {{ openconext_releases_dir }}/OpenConext-engineblock/ldap/changes/addDeprovisionWarningSentAttributes.ldif
  register: add_deprevision_output
  changed_when: "add_deprevision_output.rc != 20"
  failed_when: "add_deprevision_output.rc not in [20,0]"
  tags: ldap


- name: import entries
  shell: ldapmodify -x -D cn=admin,cn=config -h {{ ldap_host }} -w {{ ldap_password }} -f {{ openconext_releases_dir }}/OpenConext-engineblock/ldap/changes/addCollabPersonUUID.ldif
  register: add_collab_output
  changed_when: "add_collab_output.rc != 20"
  failed_when: "add_collab_output.rc not in [20,0]"
  tags: ldap

