# The suffix (dc=surfconext,dc=nl) of these users must be equal
ldap:
  user_cn: ro # needs to correspond with cn of ldap_user
  password_sha: "{SSHA}pWk1Ibd4w84++95xjuXXbrbzxr4eAPNM" # needs to correspond with ldap_password
  admin:
    org: surfconext
    user: "{{ ldap_admin_user }}"
    # suffix needs to be the same as in the user
    suffix: "dc=surfconext,dc=nl"
    password: "{{ ldap_admin_password }}"
    password_sha: "{SSHA}ZTcz1DhpiYwfj4ZMF4+t/MuxZKQno/6V" # this has to match value in password. Use slappasswd -s 'unecrypted password' to generate
  engine:
    user: "{{ engine_ldap_bind_dn }}"
    user_cn: engine
    password: "{{ engine_ldap_password }}"
    password_sha: "{SSHA}XlAxDselBl2tk/Ohm7W+nJaSXoNhdElf" # this has to match value in password. Use slappasswd -s 'unecrypted password' to generate
  grouper:
    unit_test_user: gadget

