---
- name: Download current version
  get_url: url="{{ engine_download_url }}" dest="{{ engine_build_path }}"

- name: Install current version
  unarchive: src={{ engine_build_path }} dest={{ openconext_releases_dir }} copy=no

- name: Install Apache vhost
  template: src={{ item }}.j2 dest=/etc/httpd/conf.d/{{ item }}
  with_items:
    - engine.conf
    - profile.conf
  notify:
    - restart httpd


- name: copy over the engineblock keys
  copy: content="{{ lookup('file', 'files/' + env_name + '/certs/' + item.value.privateKey) | vault }}" dest={{ item.value.privateFile }}
  with_dict: engine_keys

- name: copy engineblock certificates to correct location
  copy: src=files/{{ env_name }}/certs/{{ item.value.publicKey }} dest={{ item.value.publicFile }}
  with_dict: engine_keys

- name: Configure EngineBlock
  template: src={{ item }}.j2 dest=/etc/openconext/{{ item }}
  with_items:
    - engineblock.ini
#
#- name: Run EngineBlock migrations
#  command: ./bin/migrate
#  args:
#    chdir: "{{ engine_release_dir }}"
#
#- name: Activate new EngineBlock
#  file: src={{ engine_release_dir }} dest={{ engine_current_release_symlink }} state=link
#  notify:
#    - restart apache
#
#- name: Legacy 4.2.0
#  include: 4.2.0-post.yml
