- name: Deploy | Download snapshot
  get_url:
    url: "{{ maven_snapshot_repo }}/org/openconext/authz-admin/{{ authz_admin_version }}-SNAPSHOT/authz-admin-{{ authz_admin_version }}-{{ authz_admin_snapshot_timestamp }}.jar"
    dest: "{{ authz_admin_dir }}/authz-admin-{{ authz_admin_version }}-{{ authz_admin_snapshot_timestamp }}.jar"
    owner: "{{ java_app.user }}"
    group: "{{ java_app.user }}"
  register: app_released

- include: switch-version.yml app_service_name={{ java_app.name }}
  when: app_released.changed
