---
keytool:
  current_certificate:
    alias: "openconext cacert"
    file: "{{ tls.cert_path }}/{{ tls_https.bundle_name }}"
  # revoked_certificates contains a list of aliases of certificates that must be revoked.
  # You can not reuse alias names.
  # revoked_certificates:
  #   - "alias to revoke"

tomcat_install_dir: "{{ tomcat.install_dir }}"
tomcat_properties_dir: "{{ tomcat.properties_dir }}"
tomcat_share_dir: "{{ tomcat.share_dir }}"
tomcat_service_name: "{{ tomcat.service_name }}"
