---

- name: Install mysql server
  yum: name={{ item }} state=present
  with_items:
     - mysql-server.x86_64
  tags: mysql

- name: Start and enable mysql
  service: name=mysqld state=started enabled=yes
  tags: mysql

- name: Set mysql root password for all root accounts
  mysql_user: name=root password={{ mysql_root_password | vault(env) }} priv=*.*:ALL,GRANT
  tags: mysql

- name: MySQL my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf mode=0600 owner=root group=root
  tags: mysql

- name: delete anonymous MySQL server user
  mysql_user: user="" state="absent" login_user=root login_password={{ mysql_root_password | vault(env) }}
  tags: mysql

- name: delete anonymous MySQL server user for localhost
  mysql_user: user="" state="absent" login_user=root login_password={{ mysql_root_password | vault(env) }}
  tags: mysql

- name: remove the MySQL test database
  mysql_db: db=test state=absent login_user=root login_password={{ mysql_root_password | vault(env) }}
  tags: mysql

- name: Create database
  mysql_db: name={{ item }} state=present
  with_items:
    - "{{ databases.names }}"
  tags: mysql

- name: Create database user
  mysql_user: name={{ item.name }} host={{ item.host }} password={{ item.password | vault(env) }} priv={{ item.db_name }}.*:ALL state=present
  with_items:
    - "{{ databases.users }}"
  tags: mysql

