---
- name: create static dir
  file: path=/var/www/static state=directory

- name: create static idp image directory
  file: path=/var/www/static/logos/idp state=directory owner={{ static.sync_user }}
 
- name: create static sp image directory
  file: path=/var/www/static/logos/sp state=directory owner={{ static.sync_user }}

- name: copy media files
  copy: src=media dest=/var/www/static

- name: symlink legacy idp and sp logo locations
  file: src=../logos/{{ item }} dest=/var/www/static/media/{{ item }} state=link
  with_items:
    - 'idp'
    - 'sp'

- name: Create SSL key
  copy: content="{{ backend_tls_key }}" dest={{ tls.cert_private_path }}/backend.{{ base_domain  }}.key mode=0600 owner=root
  when: haproxy_backend_tls is defined

- name: Create SSL certificate 
  copy: src={{ inventory_dir }}/files/certs/backend.{{ base_domain }}.pem dest="{{ tls.cert_path }}/backend.{{ base_domain}}.pem"
  when: haproxy_backend_tls is defined

- name: copy apache config
  template: src=static.conf.j2 dest=/etc/httpd/conf.d/static.conf
  notify: reload httpd
