---
- name: Create user
  user: name=attribute-mapper system=yes home={{ attribute_mapper_dir }} shell=/sbin/nologin

- name: Copy start script
  template: src=templates/spring-boot.j2 dest=/etc/init.d/{{ springapp_service_name }} mode=0755
  notify: restart attribute-mapper

- name: enable attribute-mapper service
  service: name=attribute-mapper enabled=yes

- name: Create logging directory
  file: path=/var/log/{{ springapp_service_name }} state=directory owner=attribute-mapper group=attribute-mapper mode=0755

- include: ../../../tasks/springbootapp/install-release.yml
  when: "attribute_mapper_snapshot_timestamp == '' and attribute_mapper_local_jar == ''"

- include: ../../../tasks/springbootapp/install-snapshot.yml
  when: "attribute_mapper_snapshot_timestamp != '' and attribute_mapper_local_jar == ''"

- include: ../../../tasks/springbootapp/install-local.yml
  when: "attribute_mapper_local_jar != ''"

- name: Copy logging config
  template: src=logback.xml.j2 dest={{ attribute_mapper_dir }}/logback.xml owner=attribute-mapper group=attribute-mapper mode=0740
  notify: restart attribute-mapper

- name: Copy application config
  template: src=application.yml.j2 dest={{ attribute_mapper_dir }}/application.yml owner=attribute-mapper group=attribute-mapper mode=0740
  notify: restart attribute-mapper

- name: copy apache config
  template: src=attribute_mapper.conf.j2 dest=/etc/httpd/conf.d/attribute_mapper.conf
  notify: reload httpd

- name: ensure the service is started
  service: name=attribute-mapper enabled=yes state=started
