---
- name: set timezone for java apps that may be started on the commandline
  template: src=jdk-timezone.sh.j2 dest=/etc/profile.d/jdk-timezone.sh owner=root group=root mode=0644

- name: Install java
  yum: name={{ item }} state=present
  with_items:
    - java-1.8.0-openjdk-devel.x86_64
    - java-1.7.0-openjdk-devel
  tags: java

- name: Link JDK alternatives to 1.7
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6") or 
        (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  file: src=/usr/lib/jvm/jre-1.7.0-openjdk.x86_64/{{ item.path }} dest=/usr/bin/{{ item.name }} state=link force=yes
  with_items:
      - { name: 'java', path: 'bin/java' }
      - { name: 'javaws', path: 'bin/javaws' }
      - { name: 'keytool', path: 'bin/keytool' }
  tags: java

- name: Link JDK alternatives to 1.7
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  file: src=/usr/lib/jvm/jre-1.7.0-openjdk/{{ item.path }} dest=/usr/bin/{{ item.name }} state=link force=yes
  with_items:
      - { name: 'java', path: 'bin/java' }
      - { name: 'javaws', path: 'bin/javaws' }
      - { name: 'keytool', path: 'bin/keytool' }
  tags: java

