---
- name: Add group {{ serviceregistry_fpm_user }}
  group: name={{ serviceregistry_fpm_user }} state=present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Add user {{ serviceregistry_fpm_user }}
  user: name={{ serviceregistry_fpm_user }} group={{ serviceregistry_fpm_user }} createhome=no state=present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Install memcached and required modules
  yum: name=memcached state=present

- name: Install - Installation directory
  file: path={{ janus_installation_dir }} state=directory
  register: janusInstallationDir

- name: Install SSP - Download archive
  get_url: url="{{ janus_ssp_download_base_url }}/{{ janus_ssp_tar_file }}" dest="{{ janus_ssp_tar_location }}"
  register: janusSSP

- debug: var=janusInstallationDir

- debug: var=janusSSP

- include: simplesamlphp.yml
  when: janusInstallationDir.changed or janusSSP.changed

- name: Install JANUS - Download archive
  get_url: url="{{ janus_download_base_url }}/{{ janus_tar_file }}" dest="{{ janus_tar_location }}"
  register: janusDownload

- name: Install JANUS - Create dir
  file: path={{ janus_dir }} state=directory
  register: janusDir

- debug: var=janusDownload

- debug: var=janusDir

# eb_sr_sql is only set if the vm_only_provision_eb_sr tasks have been run 
- include: janus.yml
  when: janusDownload.changed or janusDir.changed or ( eb_sr_sql is defined and eb_sr_sql.changed ) 
