---
- name: copy teams configuration
  template: src=coin-teams.properties.j2 dest={{ tomcat.install_dir }}/{{ tomcat.properties_dir }}/coin-teams.properties
  tags: dashboard
  notify: restart tomcat

- name: copy teams logging configuration
  copy: src=teams-logback.xml dest={{ tomcat.install_dir }}/{{ tomcat.properties_dir }}/teams-logback.xml group=tomcat owner=tomcat
  notify: restart tomcat

- name: copy virtual host config
  template: src=teams.conf.j2 dest=/etc/httpd/conf.d/teams.conf
  notify: restart httpd

- name: copy grouper provision script for teams
  copy: src={{ item }} dest=~/{{ item }}
  with_items:
    - create-stems.gsh

- name: provision grouper for teams
  shell: bin/gsh ~/create-stems.gsh
  register: gsh_output
  changed_when: gsh_output.stderr != ''
  args:
    chdir: /opt/www/grouper-shell
