---
attribute_aggregationdir: /opt/teams
attribute_aggregationversion: ''
attribute_aggregationsnapshot_timestamp: ''
attribute_aggregationlocal_jar: ''
attribute_aggregationjar: teams-current.jar
attribute_aggregationrandom_source: 'file:///dev/urandom'
attribute_aggregationcronjobmaster: true
