---
- name: Deploying {{ app_name }} | Bring warfile to downloads directory
  copy: src={{ app_local_war }} dest=~/{{ deploy_name }}-candidate.war
  register: local_app_warfile
  when: app_local_war != ''

