# Default variables used to configure Profile
# These can be overwritten via group or extra vars

# Version of Profile that is installable by this role
# E.g. profile_version: x.y.z

# Profile installer specific variables
profile_version_dir: "{{ profile_version | replace('/', '-') }}"
profile_branch_dir: "{{ openconext_builds_dir }}/OpenConext-profile-{{ profile_branch | replace('/', '-') }}"
profile_release_dir: "{{ openconext_releases_dir }}/OpenConext-profile-{{ profile_version_dir }}"
profile_build_path: "{{ openconext_builds_dir }}/OpenConext-profile-{{ profile_version_dir }}.tar.gz"
profile_download_url: "https://github.com/OpenConext/OpenConext-profile/releases/download/{{ profile_version }}/OpenConext-profile-{{ profile_version_dir }}.tar.gz"
profile_current_release_symlink: "{{ openconext_releases_dir }}/OpenConext-profile"

# Domain under which profile can be found
profile_domain: profile.{{ base_domain }}

# Cache and log paths
profile_symfony_cache_path: "/tmp/profile/symfony-cache/{{ profile_version }}"
profile_symfony_log_path: "/var/log/profile"

# Secret used by application for adding entropy to security related operations
profile_secret: secret

# Language code for user locale to be set by default
# E.g. profile_default_locale: en
profile_default_locale: en

# IP-address and domain of Engine API to enable Profile to send API calls
engine_api_domain: engine-api.{{ base_domain }}
engine_api_verify_ssl: true

# Paths of public and private key used for sending SAML AuthnRequests
profile_saml_sp_publickey: ../vendor/surfnet/stepup-saml-bundle/src/Resources/keys/development_publickey.cer
profile_saml_sp_privatekey: ../vendor/surfnet/stepup-saml-bundle/src/Resources/keys/development_privatekey.pem

# Paths of public and private key used for signing metadata
profile_saml_metadata_publickey: ../vendor/surfnet/stepup-saml-bundle/src/Resources/keys/development_publickey.cer
profile_saml_metadata_privatekey: ../vendor/surfnet/stepup-saml-bundle/src/Resources/keys/development_privatekey.pem

# Domain under which EngineBlock can be found
engine_domain: engine.{{ base_domain }}

# EntityID of remote identity provider
engine_profile_idp_entityid: https://{{ engine_domain }}/authentication/idp/metadata

# URL for remote identity provider's single sign on
engine_profile_idp_sso_url: https://{{ engine_domain }}/authentication/idp/single-sign-on

# Contents of certificate used to sign the AuthnResponse with
# FIXME: is env specific
engine_profile_idp_certificate: MIIC+zCCAmSgAwIBAgIJAPJvLjQsRR4iMA0GCSqGSIb3DQEBBQUAMF0xCzAJBgNVBAYTAk5MMRAwDgYDVQQIEwdVdHJlY2h0MRAwDgYDVQQHEwdVdHJlY2h0MRAwDgYDVQQKEwdTVVJGbmV0MRgwFgYDVQQDEw90ZXN0MiBzYW1sIGNlcnQwHhcNMTUwMzI0MTQwMzE3WhcNMjUwMzIxMTQwMzE3WjBdMQswCQYDVQQGEwJOTDEQMA4GA1UECBMHVXRyZWNodDEQMA4GA1UEBxMHVXRyZWNodDEQMA4GA1UEChMHU1VSRm5ldDEYMBYGA1UEAxMPdGVzdDIgc2FtbCBjZXJ0MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCxKYrnW8NwqdRwRwaHulueL69gQFTJbdfoASLhYie2bOioJyJw1f+cAvpjsl4SVYpvEseIetXH8Lgpk7K73PkDJL8dFg4sEjFF6jgmjrOES3ox/gtTd9d/VwPHI/vPIcGy1sbVJ4pEMFl5d8GOAzoJkNWdPj9wV4rv4uv35May8wIDAQABo4HCMIG/MB0GA1UdDgQWBBTTIaPwpKpJlY8eIMSzNRZUjStbijCBjwYDVR0jBIGHMIGEgBTTIaPwpKpJlY8eIMSzNRZUjStbiqFhpF8wXTELMAkGA1UEBhMCTkwxEDAOBgNVBAgTB1V0cmVjaHQxEDAOBgNVBAcTB1V0cmVjaHQxEDAOBgNVBAoTB1NVUkZuZXQxGDAWBgNVBAMTD3Rlc3QyIHNhbWwgY2VydIIJAPJvLjQsRR4iMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAK8EvTU0LgHJsSugorOemgRlppMfJAeOmuuZNhSMY2QhumFOZpaAb8NFIwUKUVyyJnSo7k6ktHCKI94sQs976242hTDDYEwWJD9HhAsAqOo21Ua8gZT38/wm62e3KgrKXvnljAbKPXDXJM4akz7y6H6wvvIGT6f0f0iJWHq34jww= 

profile_fpm_user: profile
profile_fpm_port: 802
