---
- name: Install httpd and required modules
  yum: name={{ item }} state=present
  with_items:
     - httpd
  tags: httpd

- name: Copy default config files
  copy: src={{ item }} dest=/etc/httpd/conf.d/{{ item }}
  tags: httpd
  with_items:
    - 01_default.conf
  notify: reload httpd

- name: Copy the config file
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  tags: httpd
  notify: reload httpd

- name: Remove default conf files apache
  file: path=/etc/httpd/conf.d/{{ item }} state=absent
  with_items:
    - welcome.conf

- name: Remove default /var/www folders
  file: path=/var/www/{{ item }} state=absent
  with_items:
    - cgi-bin
    - error
    - html
    - icons

- name: enable httpd
  service: name={{ item }} enabled=yes
  with_items:
       - httpd
