---
- name: Ensure the directories exist
  file: path={{ item }} state=directory
  with_items:
  - "{{ openconext_builds_dir }}"
  - "{{ openconext_configs_dir }}"
  - "{{ openconext_logging_dir }}"
  - "{{ openconext_releases_dir }}"

- name: Symlink /etc/surfconext to /etc/openconext
  file: src={{ openconext_configs_dir }} path=/etc/surfconext state=link
