---
- name: Install tomcat
  yum: name="tomcat6" state="present"
  tags: tomcat

- name: Set TZ variable in tomcat's init-environment
  lineinfile:
    dest: "{{ tomcat_install_dir }}/tomcat6.conf"
    line: "TZ=\"{{ timezone }}\""
    state: present
    create: no
  notify: restart tomcat
  tags: tomcat

- name: Add AJP to connect to Apache
  copy: src={{ item }} dest=/etc/httpd/conf.d/{{ item }}
  with_items:
    - ajp.conf
  notify: restart tomcat

- name: Create directory for application config
  file: state=directory path={{ tomcat_install_dir }}/{{ tomcat_properties_dir }} owner=tomcat group=tomcat
  tags: tomcat

- name: Create directory for wars
  file: state=directory path={{ tomcat_install_dir }}/wars owner=tomcat group=tomcat
  tags: tomcat

- name: "DEPRECATED: Create shared directory for jars"
  file: state=directory path={{ tomcat_share_dir }}/shared owner=tomcat group=tomcat
  notify: restart tomcat
  tags: tomcat

- name: "DEPRECATED: Create shared lib directory for jars"
  file: state=directory path={{ tomcat_share_dir }}/shared/lib owner=tomcat group=tomcat
  notify: restart tomcat
  tags: tomcat

- name: Copy tomcat config
  template: src={{ item }}.j2 dest={{ tomcat_install_dir }}/{{ item }}
  with_items:
    - server.xml
    - catalina.properties
    - tomcat-users.xml
  notify: restart tomcat
  tags: tomcat

- name: Copy sysconfig tomcat
  template: src=tomcat6.conf.j2 dest={{ tomcat_install_dir }}/tomcat6.conf
  notify: restart tomcat
  tags: tomcat

- name: Unused webapps dir must still be present
  file: path=/var/lib/tomcat6/webapps state=directory group=tomcat owner=tomcat
  tags: tomcat

- name: check if there are any keys to revoke
  command: keytool -list -alias "{{ item }}" -keystore /etc/pki/java/cacerts -storepass {{ keystore_password | vault(env) }}
  with_items: keytool.revoked_certificates
  when: keytool.revoked_certificates is defined
  register: certificates
  tags: tomcat

- name: delete revoked certificates
  command: keytool -delete -alias "{{ item }}" -keystore /etc/pki/java/cacerts -storepass {{ keystore_password | vault(env) }}
  when: certificates is defined and item.rc == 0
  with_items: certificates.results
  notify: restart tomcat
  tags: tomcat

- name: check if the certificate already exists in the keystore
  command: keytool -list -alias "{{ item.alias }}" -keystore /etc/pki/java/cacerts -storepass {{ keystore_password | vault(env) }}
  register: check_certificate_exists
  ignore_errors: yes
  changed_when: False
  with_items: keytool.current_certificates
  tags: tomcat

- name: populate java keystore so that our machine-clients can talk to REST services provided by openconext
  command: keytool -import -noprompt -alias "{{ item.item.alias }}" -file {{ item.item.file }} -trustcacerts -keystore /etc/pki/java/cacerts -storepass {{ keystore_password | vault(env) }}
  when: item.rc != 0
  with_items: check_certificate_exists["results"]
  notify: restart tomcat
  tags: tomcat

- name: Start and enable tomcat6
  service: name={{ tomcat_service_name }} state=started enabled=yes
  notify: restart tomcat
  tags: tomcat
