---
env: ebhost

smtp_server: localhost
error_mail_to: devnull@example.org

php_display_errors: 1
apache_server_admin: root@localhost
janus_ssp_technicalcontact_name: "Technical Contact"
janus_ssp_technicalcontact_email: "root@localhost"
janus_ssp_managingcontact_name: "Managing Contact"
janus_ssp_managingcontact_email: "root@localhost"
engine_idp_debugging_email_address: root@localhost

profile_version: 0.3.0
engine_version: "5.0.0-rc1"

databases:
  names:
    - "{{ engine_database_name }}"
    - "{{ janus_database_name }}"
  users:
    - { name: "{{ engine_database_user }}", db_name: "{{ engine_database_name }}", password: "{{ mysql_passwords.eb }}" }
    - { name: "{{ janus_database_user }}", db_name: "{{ janus_database_name }}", password: "{{ mysql_passwords.sr }}" }

tls:
  cert_path: /etc/pki/tls/certs
  cert_path_ca: /etc/pki/ca-trust/source/anchors
  cert_private_path: /etc/pki/tls/private


tls_ca: star.{{ base_domain }}_ca.pem

tls_star_cert_bundle_name: star.{{ base_domain }}_ca_bundle.pem
tls_star_cert: star.{{ base_domain }}.pem
tls_star_cert_key: star.{{ base_domain }}.key

tls_https:
  - name: star
    key_name: "star.{{ base_domain }}.key"
    crt_name: "star.{{ base_domain }}.pem"
    bundle_name: "star.{{ base_domain }}_ca_bundle.pem"
    key_content: "{{ https_star_private_key }}"

engine_janus_user: engineblock

engine_database_name: eb
engine_database_host: "{{ mysql_host }}"
engine_database_port: 3306
engine_database_user: ebrw
engine_database_password: "{{ mysql_passwords.eb }}"

engine_apache_environment: test
engine_apache_symfony_environment: prod

janus_database_name: sr
janus_database_host: "{{ mysql_host }}"
janus_database_user: srrw
janus_database_password: "{{ mysql_passwords.sr }}"
janus_no_federative_login: 1
janus_default_sp: "example-auth"

engine_janus_cache_lifetime: 0

engine_trusted_proxy_ips:
  - 192.168.100.1
  - 10.0.0.1
#
engine_keys:
  default:
    privateFile: /etc/openconext/engineblock.pem
    publicKey: engineblock.crt
    publicFile: /etc/openconext/engineblock.crt

engine_block:
  metadataRepositories:
    - {
        index: 0,
        type: "janus",
        value: "JanusRestV1"
      }

profile_apache_symfony_environment: prod
# Engine's assertion signing certificate:
engine_profile_idp_certificate:

engine_feature_ldap_integration: 0

engineblock:
  idp_url: https://engine.{{ base_domain }}/authentication/idp/single-sign-on
  idp_entity_id: https://engine.{{ base_domain }}/authentication/idp/metadata
  without_java: true
  external_idp:
    name: "SPIP"
    entityid: "https://spip.muisit.nl/saml2/idp/metadata.php"
    sso: "https://spip.muisit.nl/saml2/idp/SSOService.php"
    binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    certificate: "MIID8zCCAtugAwIBAgIJANycpk64MSXjMA0GCSqGSIb3DQEBCwUAMIGPMQswCQYDVQQGEwJOTDETMBEGA1UECAwKR2VsZGVybGFuZDETMBEGA1UEBwwKV2FnZW5pbmdlbjEQMA4GA1UECgwHbXVpcyBJVDEMMAoGA1UECwwDSUNUMRcwFQYDVQQDDA5zcGlwLm11aXNpdC5ubDEdMBsGCSqGSIb3DQEJARYOc3BpcEBtdWlzaXQubmwwHhcNMTYwNjA5MDkyNDE3WhcNMjYwNjA5MDkyNDE3WjCBjzELMAkGA1UEBhMCTkwxEzARBgNVBAgMCkdlbGRlcmxhbmQxEzARBgNVBAcMCldhZ2VuaW5nZW4xEDAOBgNVBAoMB211aXMgSVQxDDAKBgNVBAsMA0lDVDEXMBUGA1UEAwwOc3BpcC5tdWlzaXQubmwxHTAbBgkqhkiG9w0BCQEWDnNwaXBAbXVpc2l0Lm5sMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsNsruaxSPHQGtzI+HQf2DqytAWTmB2JzyW3NvYgnPyH2KtlKXZvsInzx7QfsZBUKZaLwvncGmqBxr1xMbYBAdlyzERcV4db0CGPdzv0sXYqQ+DPzSAKsXSIQW6XNidtFNBP1Pae8gcYfHb4DeLBT+ip/sxSCbegvbjdPFHkk+CAUp9lNXg6TZ0dAm7E4SjBFq2rbQMsTIiCpzvvi6ODzECRcOSQep6j3pGW+BSWOgdZjp50iDLZwRHQ1xOrYG3Etz3TpfsC2TPU/O+Au1gc+nmbal+FkfD4xgcVTt3swV9MLzg7wrI/Q24089Gn5I0ijIWe9yH9S0U71bnE+aAB7/QIDAQABo1AwTjAdBgNVHQ4EFgQUb7TNTPJIcVRTpXABZ4GAeSxUD1AwHwYDVR0jBBgwFoAUb7TNTPJIcVRTpXABZ4GAeSxUD1AwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAdbbSXwah2Hi+iDNtzOi2THvTmQ6l/ig3qr8kKhpxBlBlTAODsO0M5KM7Q6Hfv1agExKZIDD9BpiCiA/paMafrIaoxapi3+E+bazJ6I6y53L7CMbjN1sbgIDj5nwxhQVnXlNFBT2FLCQ7CvPDY8QTvfn9bA4EUaVMDHqB26fM5TJw2Z1Te2EhJifDf7qREvagzrl+7OepQp3tXOxedkxi7e42PgL1TIL1Qii5M9L5DgIa2y5wEtLlWvNbO8/k3WE5CziFz66HEamQgCiM9fq0PT1+z7BYEMuJ/aIMWYE1GjgafzOyM6qQl1xeTO5drjEXDyp9NPoFZrljpiIURCiCkA=="
    timestamp: "1970-01-01T00:00:00+00:00"
    ip: "127.0.0.1"
    email: "info@muisit.nl"


##
# VM config for the api app
##
api:
  janus:
    user: "{{ engine_janus_user }}"
    secret: "{{ engine_janus_secret }}"
    uri: https://serviceregistry.{{ base_domain }}/simplesaml/module.php/janus/services/rest/
  engineblock:
    user: "{{ engine_database_user }}"
    url: jdbc:mysql://{{ engine_database_host }}:3306/{{ engine_database_name }}
    password: "{{ engine_database_password }}"
  staticContentBasePath: https://static.{{ base_domain }}
  saml:
    entityId: https://api.{{ base_domain }}/
    assertionConsumerURI: https://api.{{ base_domain }}/v1/assertionConsumer
  ehcache:
    path: /tmp

php_servers:
   - { ip: "192.168.100.10", label: "php"}
