- name: "Disable firewalld"
  service: name=firewalld enabled=no state=stopped

- name: Install iptables and ip6tables
  yum: name={{item}} state=present
  with_items:
  - iptables-services

- name: Put iptables
  template: src=iptables.j2 dest='/etc/sysconfig/iptables'
  notify:
  - restart iptables

- name: Put ip6tables
  template: src=ip6tables.j2 dest='/etc/sysconfig/ip6tables'
  notify:
  - restart ip6tables

- name: Start and enable services ntpd, iptables, iptables6
  service: name={{item}} state=started enabled=true
  with_items:
  - iptables
  - ip6tables

# journald binary logs corrupt on specific engineblock messages.
# disabling compression fixes that issue
- name: Disable journald compression
  copy: src=journald.conf dest='/etc/systemd/journald.conf' 
  notify: 
  - restart journald

